# Generated by Django 2.0 on 2022-11-09 14:19

from django.db import migrations, models
import django.db.models.deletion
import patterns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('editor', models.TextField(verbose_name='Editor')),
                ('abstract', models.TextField()),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('structure', models.ImageField(upload_to=patterns.models.structure_path, verbose_name='Estructura')),
                ('intent', models.TextField(verbose_name='Intención')),
                ('motivation', models.TextField(verbose_name='Motivación')),
                ('applicability', models.TextField(verbose_name='Aplicación')),
                ('paricipants', models.TextField(verbose_name='Participantes')),
                ('consequences', models.TextField(verbose_name='Consequencias')),
                ('example', models.TextField(verbose_name='Ejemplo')),
                ('related_pattens', models.TextField(verbose_name='Patrones relacionados')),
                ('source_credit', models.TextField(verbose_name='Creditos a la fuente')),
            ],
            options={
                'verbose_name': 'Patrón',
                'verbose_name_plural': 'Patrones',
            },
        ),
        migrations.CreateModel(
            name='PatternType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de patrón',
                'verbose_name_plural': 'Tipos de patrones',
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Contrato inteligentes',
                'verbose_name_plural': 'Contratos inteligentes',
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Caso de uso',
                'verbose_name_plural': 'Casos de uso',
            },
        ),
        migrations.CreateModel(
            name='UseCaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria de caso de uso',
                'verbose_name_plural': 'Categorias de caso de uso',
            },
        ),
        migrations.AddField(
            model_name='usecase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patterns.UseCaseCategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='smartcontract',
            name='business_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patterns.UseCase', verbose_name='Caso de uso'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patterns.SmartContract', verbose_name='Catálogo'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patterns.PatternType', verbose_name='Tipo de Patrón'),
        ),
        migrations.AddField(
            model_name='paper',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patterns.SmartContract', verbose_name='Catálogo'),
        ),
        migrations.AlterUniqueTogether(
            name='pattern',
            unique_together={('name', 'type')},
        ),
    ]
