# Generated by Django 4.0.5 on 2022-08-15 15:18

from django.db import migrations, models
import memoryDB.models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='db',
            field=models.FileField(upload_to=memoryDB.models.structure_path, verbose_name='Database'),
        ),
    ]
