# Generated by Django 4.0.5 on 2022-08-15 17:19

from django.db import migrations, models
import memoryDB.models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryDB', '0002_alter_config_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='db',
            field=models.FileField(storage=memoryDB.models.ConstantNamesStorage(), upload_to=memoryDB.models.structure_path, verbose_name='Database'),
        ),
    ]
