# Generated by Django 2.0 on 2022-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryDB', '0003_alter_config_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
