# Generated by Django 4.1.3 on 2023-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryDB', '0004_auto_20221109_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
